// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsr2frzO4U_zVNLHXau0AkzE52V-yPtE',
    appId: '1:326086033810:web:8b9c670a574113e0abc14b',
    messagingSenderId: '326086033810',
    projectId: 'text-neck-ai',
    authDomain: 'text-neck-ai.firebaseapp.com',
    storageBucket: 'text-neck-ai.firebasestorage.app',
    measurementId: 'G-94E680G29K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqyDD4xkJXyBDcUwMjUUAjjSiIN1--OG0',
    appId: '1:326086033810:android:3c6bc6b50acf4c19abc14b',
    messagingSenderId: '326086033810',
    projectId: 'text-neck-ai',
    storageBucket: 'text-neck-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5wmOI5-XEdAMEDHF2ioXjb3k52QaYpQ',
    appId: '1:326086033810:ios:8e7532b2c81a2a0eabc14b',
    messagingSenderId: '326086033810',
    projectId: 'text-neck-ai',
    storageBucket: 'text-neck-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx5wmOI5-XEdAMEDHF2ioXjb3k52QaYpQ',
    appId: '1:326086033810:ios:8e7532b2c81a2a0eabc14b',
    messagingSenderId: '326086033810',
    projectId: 'text-neck-ai',
    storageBucket: 'text-neck-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCsr2frzO4U_zVNLHXau0AkzE52V-yPtE',
    appId: '1:326086033810:web:a2cab018f053baf0abc14b',
    messagingSenderId: '326086033810',
    projectId: 'text-neck-ai',
    authDomain: 'text-neck-ai.firebaseapp.com',
    storageBucket: 'text-neck-ai.firebasestorage.app',
    measurementId: 'G-L9R9M95LDL',
  );
}
